apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-notification-service

resources:
  - ../../../base/notification-service
  - namespace.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification-service
      spec:
        template:
          spec:
            containers:
              - name: notification-service
                env:
                  - name: ENV_NAME
                    value: "dev"
    target:
      kind: Deployment
      name: notification-service

