apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production-user-service

resources:
  - ../../../base/user-service
  - namespace.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: user-service
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: user-service
                env:
                  - name: ENV_NAME
                    value: "production"
    target:
      kind: Deployment
      name: user-service

